### ISSUE TITLE
выбрать текст

### ISSUE THREAD

**Issue by gree-gorey** [gree-gorey/pos-tagging#1]
выбрать текст

**Comment by tanya-ling** [comment]
Это Житие Аввакума.

[avv.txt.gz](https://github.com/gree-gorey/pos-tagging/files/180964/avv.txt.gz)

Разметка тут в трех разных форматах, не знаю, из какого Грише будет удобнее конвертивать (на мой взгляд conll всех лучше и красивей).

[avv.conll.gz](https://github.com/gree-gorey/pos-tagging/files/180962/avv.conll.gz)
[avv.tiger.gz](https://github.com/gree-gorey/pos-tagging/files/180963/avv.tiger.gz)
[avv.xml.gz](https://github.com/gree-gorey/pos-tagging/files/180965/avv.xml.gz)

Описание conll - http://ilk.uvt.nl/conll/#dataformat
Описание tiger - https://drive.google.com/open?id=0B1TamOF1pBmXa19PdE5rTENxMFk
Описание proiel - https://drive.google.com/open?id=0B1TamOF1pBmXR0FmV0hDYVhQanM

**Comment by gree-gorey** [comment]
мне тоже conll больше нравится)

**Comment by tanya-ling** [comment]
вот то что выдает мой парсер - https://drive.google.com/open?id=0B1TamOF1pBmXd0Y1czNWbkJ6RWs
https://drive.google.com/open?id=0B1TamOF1pBmXU3VxR0x4Q2I5Tnc

(да, я знаю, что довольно странно, что распаршенные и не распаршенные слова в разных файлах, нет индексации и вообще, но почему-то Тимофей давным давно сделал так и это особенно никому не мешает)

Там сейчас что-то глючит и часть слов, которые должны парсится, не распознаются, но я очень хочу спать. В принципе тебе должно быть всё равно, на чем делать перевод; я завтра днем вышлю нормальные варианты.

**Comment by gree-gorey** [comment]
а, ну понятно почему он ругался на твой csv - потому что внутри это xml :)

**Comment by gree-gorey** [comment]
[вот тут](https://github.com/gree-gorey/pos-tagging/tree/master/tested_from) я положил твой файл
[вот тут](https://github.com/gree-gorey/pos-tagging/tree/master/gold_from) файл золотого стандарта

[скрипт для парсинга файлов](https://github.com/gree-gorey/pos-tagging/blob/master/converter.py) почти готов. Дальше нужно думать о конвертации тегов. #2

**Comment by tanya-ling** [comment]
Нет, он не берет даже csv, которые на самом деле txt
