### ISSUE TITLE
сделать перевод тегов

### ISSUE THREAD

**Issue by gree-gorey** [gree-gorey/pos-tagging#2]
можно ориентироваться на файл, который я скинула в беседу, и еще второй для морфологии сейчас скину. В общем, совершенно необяательно переводить юни парсер в формат зс. Можно сделать наоборот. Или оба свести к чему-то промежуточному. Будут вещи, которые нельзя свести, не потеряв точности, это нормально.

**Comment by tanya-ling** [comment]
[таблица соответствия частей речи](https://github.com/gree-gorey/pos-tagging/blob/master/tag_correspondence.csv)

**Comment by tanya-ling** [comment]
[это список тегов юни парсера](https://github.com/gree-gorey/pos-tagging/blob/master/tag_list.txt)

**Comment by tanya-ling** [comment]
хорошо, если файл для прохождения глазами будет выглядеть [как-то так](https://docs.google.com/spreadsheets/d/1KSDH7mkStvOYaPkoAs1lQxNUwneCOzKBow0VdTMzxwo/edit#gid=264084611) (без ословского, разумеется)

**Comment by tanya-ling** [comment]
[вот тут](https://docs.google.com/document/d/16tJ_OVX_1nVa4WdOu6Um_nLUgA4vLjQlY2RraDqNsLs/edit) можно посмотреть описание различий буквами

**Comment by gree-gorey** [comment]
короче, перевод тегов я почти закончил, мне нужно только несколько вопросов обсудить, чтобы понять как именно устроены твои теги
