### ISSUE TITLE
описать юни-парсер и его систему тегов

### ISSUE THREAD

**Issue by gree-gorey** [gree-gorey/pos-tagging#3]

**Comment by tanya-ling** [comment]
[текстовый файл](https://github.com/gree-gorey/pos-tagging/blob/master/tag_list.txt) с некотором описанием юнипарсера и тегов внутри (можно перевести тупо), список тегов.

**Comment by tanya-ling** [comment]
и [вот тут еще](https://docs.google.com/document/d/1DxRzdaRPaLMgkDTfYTkD8ydGyyTxnZLLMyKyA6PM6Hw/edit) есть про принцип работы парсера

**Comment by tanya-ling** [comment]
если что, [вот файл толдовой](https://docs.google.com/document/d/1Y4e8CbikWo3ypBLe5ZnwCTDdiBwltPtU9KFYhXtvPvU/edit) с нормальными инструкциями
