### ISSUE TITLE
пройтись глазами

### ISSUE THREAD

**Issue by gree-gorey** [gree-gorey/pos-tagging#4]
пройтись глазами по крайней мере по части сравнения и посмотреть, где перевод тегов несправедливо банит анализ. Все эти случаи написать в отчет, как то, что мы доблестно (не) побороли

**дедлайн** - 14:00 понедельника

**Comment by gree-gorey** [comment]
[файл на первые 70 слов](https://github.com/gree-gorey/pos-tagging/blob/master/result/adjacent.csv) (чтобы знать как он выглядит)

[а здесь полностью все слова](https://github.com/gree-gorey/pos-tagging/blob/master/result/adjacent_all.csv)

**Comment by tanya-ling** [comment]
довольно странно, что зс не на первой строке с разбором юни-парсера, а на какой-то рандомной
