### ISSUE TITLE
отчет

### ISSUE THREAD

**Issue by gree-gorey** [gree-gorey/pos-tagging#5]
написать прочитать получившийся отчет с начала до конца и сделать аккуратненько

[вот файл прошлого отчета](https://github.com/gree-gorey/pos-tagging/blob/master/report.md), его нужно отредактировать

**Comment by tanya-ling** [comment]
Что? а почему нужно редактировать файл прошлого отчета?

**Comment by gree-gorey** [comment]
не, ну ты просто просила документ подходящего формата для отчета создать)

это он.

**Comment by tanya-ling** [comment]
хммм. это примерно как то что я import codecs набрала один раз на первом курсе, и с тех пор копирую из программы в программу. Мой любимый подход.

**Comment by gree-gorey** [comment]
ахаха))
да. ты поняла смысл
